baseURL = 'https://munichtriathlonclub.de'
languageCode = 'de-de'
title = 'Munich Triathlon Club'
disableKinds = ['taxonomy', 'term']

[menus]
    [[menus.main]]
        name = "Home"
        pageRef = "/"
        weight = 1

    [[menus.main]]
        name = "Training"
        pageRef = "/training"
        weight = 2

    [[menus.main]]
        name = "Impressum"
        pageRef = "/impressum"
        weight = 3