baseURL = 'https://munichtriathlonclub.de'
languageCode = 'de-de'
title = 'Munich Triathlon Club'
disableKinds = ['taxonomy', 'term']

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Training"
url = "/training/"
weight = 2

[[menu.main]]
name = "Impressum"
url = "/impressum/"
weight = 3